allow_remote_control yes
listen_on unix:/tmp/kitty-sock

font_family JetBrainsMono Nerd Font
font_size 22

background_opacity 0.85

# Ctrl+C — копирование (как в ghostty)
map ctrl+c copy_to_clipboard
# Alt+C — SIGINT (прерывание процесса)
map alt+c send_text all \x03
# Ctrl+V — вставка
map ctrl+v paste_from_clipboard
# Ctrl+T — новый таб
map ctrl+t new_tab

# Скролл (Alt+MNEI)
map alt+n scroll_line_down
map alt+e scroll_line_up
map alt+shift+n scroll_page_down
map alt+shift+e scroll_page_up


# BEGIN_KITTY_THEME
# E-Ink
include current-theme.conf
# END_KITTY_THEME
