allow_remote_control yes
listen_on unix:/tmp/kitty-sock

font_family JetBrainsMono Nerd Font
font_size 22

background_opacity 0.92

# Ctrl+C — копирование (как в ghostty)
map ctrl+c copy_to_clipboard
# Alt+C — SIGINT (прерывание процесса)
map alt+c send_text all \x03
# Ctrl+V — вставка
map ctrl+v paste_from_clipboard
# Ctrl+T — новый таб
map ctrl+t new_tab


# BEGIN_KITTY_THEME
# E-Ink
include current-theme.conf
# END_KITTY_THEME
