default_profile = "default"

[profiles.default]
user_id = "@hexknife:matrix.org"
url = "https://matrix.org"

[dirs]
downloads = "/home/bekh/Downloads/"

[settings]
username_display = "username"
reaction_display = true
typing_notice_send = true
